apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-deployment1
  namespace: jenkins
  labels:
    app: gradle-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradle-deployment1
  template:
    metadata:
      labels:
        app: gradle-deployment1
    spec:
      containers:
      - name: gradle-deployment1
        image: ${REPOSITORY_TAG} 
        imagePullPolicy: Never
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: gradle-service1
  namespace: jenkins
spec:
  selector:
    app: gradle-deployment1
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 30086

  type: NodePort
      
