  
---
- name: Deploy to kubernetes cluster
  hosts: localhost
  vars:
       image_name: "{{ image }}"
       replicas: 1
       port: 8089
       NodePort: 30087
       label: hello
       namespace: project1-dev
       deployment_name: hello
       container_name: hello
       service_name: hello-service
       ingress_name: ingress-service
       host_name: microservice.com
       jar_path: ./artifactory/microservice1-0.0.1-SNAPSHOT.jar
       kube_config: ./kube_config/config
       context: minikube

  collections:
    - kubernetes.core
    
  tasks:


      - name: Run copy-jar role to copy jar files to artifactory
        include_role:
          name:  copy-jar

      - name: Run create-Dockerfile role
        include_role:
          name:  create-Dockerfile

      - name: Run docker-image role to build an image
        include_role:
          name:  docker-image

      - name: Run create-deploymentfile role
        include_role:
          name:  create-deploymentfile

      - name: Run cluster-deployment role 
        include_role:
          name:  cluster-deployment        

      - name: Run pod-status role 
        include_role:
          name:  pod-status
          
